### ISSUE TITLE
[bug] error detected during using mtf -l --show-job-log *.py

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#149]
During debugging some stuf with dovecot, I have found some bug in `/usr/bin/mtf` binary.

~~~
$ mtf -l --show-job-log *.py
--json /tmp/tmp.QKbZ6lExDQ /usr/lib/python2.7/site-packages/meta_test_family-0.7.3-py2.7.egg/moduleframework/tools/check_compose.py /usr/lib/python2.7/site-packages/meta_test_family-0.7.3-py2.7.egg/moduleframework/tools/dockerlint.py /usr/lib/python2.7/site-packages/meta_test_family-0.7.3-py2.7.egg/moduleframework/tools/helpmd_lint.py /usr/lib/python2.7/site-packages/meta_test_family-0.7.3-py2.7.egg/moduleframework/tools/modulelint.py /usr/lib/python2.7/site-packages/meta_test_family-0.7.3-py2.7.egg/moduleframework/tools/rpmvalidation.py --show-job-log dovecot.py
avocado run: error: unrecognized arguments: dovecot.py
^CTraceback (most recent call last):
  File "/usr/bin/mtf-log-parser", line 6, in <module>
~~~

It seems like mtf passing arguments to avocado in wrong order.

**Comment by phracek** [comment]
Using `mtf --show-job-log -l *.py` works properly, nevertless

**Comment by jscotka** [comment]
Hi,
yep, you found then corner case. this sequece mix args, caused by that -l is not argument, but more less just alias for set of tests,  so command `mtf -l --show-job-log *.py` does something like: `mtf pathtomodulelint/*.py --show-job-log *.py` what is wrong. `-l` should be handled at last position, or fist before last.
The problem is also that args of mtf command does not understand avocado args semantics but just pass args what does not understand thru to avocado run command, so I can show more similar examples what will leads to errors.

I suggest at least try to fix this issue with -l because probably this will be used more often and could lead to bad args position.

otherwise, it is possible to write `avocado run --show-job-log *.py` or `avocado run *.py --show-job-log`. Both works. but `avocado run *.py --show-job-log *.py` is __bad__

**Comment by psklenar** [comment]
@jscotka should I modify bash script `mtf`  somehow to parse arguments correctly?

**Comment by psklenar** [comment]
@phracek  I am going to modify script mtf to be python script with argparse. It should put together arg for avocado in its order, what do you think?

**Comment by phracek** [comment]
Go for it. Make sense to me

**Comment by phracek** [comment]
Fixed by this script https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/mtf_scheduler.py
