### ISSUE TITLE
ContainerHelper should use docker-py

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#25]
I'd suggest replacing shelling out in the `ContainerHelper` by usage of docker-py [1] library. The benefit of that is getting much better return values which can easily be inspected for results compared to subprocess results. Also it has a nice API which would be beneficial compared to hand-formatting shell commands to be executed.

[1] https://pypi.python.org/pypi/docker-py

**Comment by TomasTomecek** [comment]
Slavku, I agree with the benefits you mentioned.

Unfortunately, there is also a bunch of downsides:

1) you need have docker-py available in the environment (which is not big deal since it's packaged in Fedora)
2) docker-py is not the most stable interface (see [docker-py 2.0 release notes](https://docker-py.readthedocs.io/en/stable/change-log.html#id14)) -- docker cli has actually more stable interface
3) because of the second point, we had to rename the package in fedora so the both implementations are available

**Comment by phracek** [comment]
@hhorak What do you think about it? How do you solve it in SCL? Do you use docker-py or commands like `docker SOMETHING`

**Comment by TomasTomecek** [comment]
@phracek SCL team is using bash scripts to test their containers and they use docker CLI.

I realized I didn't express any opinion. I personally vote for using docker-py and use the version 2 interface.

**Comment by hhorak** [comment]
@phracek We actually touched pretty much this question yesterday with @ficap and @jscotka and I expressed my opinion that I'd rather use what end-users will use, which is `docker` command. Using `docker-py` might bring some new issues or would not hit other issues that we would hit in `docker` command..

**Comment by TomasTomecek** [comment]
Honzo, that shouldn't be a problem. When you look at the [ContainerHelper](https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/helpers/container_helper.py) class, there is plenty of usages of docker binary which could be easily replaced with the library. On the other hand, in the config.yaml, you can specify the (docker) command how to invoke the service for testing. Which raises the question: when the services will probably always be invoked by docker binary, does it make sense to bother with the library?

**Comment by bkabrda** [comment]
I'd say that what @hhorak says is reasonable, so let's leave things as they are.

**Comment by jscotka** [comment]
so we can close this Issue
