### ISSUE TITLE
Discourage use of RPM "module"

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#26]
Testing with `MODULE=rpm` should be discouraged in favour of nspawn (or perhaps a mock environment). The reason for this is that local environment will never allow clean reproducible tests (there are too many unknowns that MTF can't know/influence), moreover the `rpm` module does a lot of stuff to the local system (e.g. RPM installation), which might break people's systems. While I understand that this might come handy, I think that usage of the `rpm` module should be discouraged and the nspawn module should be recommended instead.

**Comment by jscotka** [comment]
Hi,
that's true. MODULE=rpm is now used for local package testing and that's why it is expected to have side effect to running system. It is typical workflow, you will get new instance of machine (virt one or bare metal in beaker) and you will directly test there and you can do anything what you want with system. 
we have to:
   * Describe it better in docs (to be clean usage of MODULE=rpm)
   * maybe rename it to better word like (direct, local) and nspawn -> nspawn-mock
   * as you wrote in capitals, that probably you are looking for nspawn, not rpm :-)

**Comment by TomasTomecek** [comment]
On Monday's workshop, there was a suggestion to have something like this. The issue was that the person is testing some SELinux policies and therefore nspawn/docker container doesn't make sense.

**Comment by bkabrda** [comment]
Yeah, I totally understand that there are valid usecases for the RPM module, but I think for most cases using nspawn would make more sense. I'd just like a big fat disclaimer somewhere, that would say "hey, using RPM module might cause you troubles, use nspawn instead".

**Comment by jscotka** [comment]
added to docs,  that it is dangerous and affect actual system
