### ISSUE TITLE
Allow removing modulemd-url from config

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#47]
I'd like to use MTF to test a docker container not built from module, therefore I'd like to ask you to make `modulemd-url` optional. Do you think this makes sense?

**Comment by TomasTomecek** [comment]
It does to me: if modulemd-url is defined, enable module-related checks, disable otherwise.

**Comment by jscotka** [comment]
It is not so easy. because modulemd file could be also found by compose-url, but yep, it make sense that in case modulemd file not there handle it as normal container, rpm repository.
It can just cause, that in case somebody forgot that -> another behaviour than expected, but still working. Is that acceptable?

**Comment by TomasTomecek** [comment]
> It can just cause, that in case somebody forgot that -> another behaviour than expected, but still working. Is that acceptable?

Well, when user explicitly says, that the artifact should be tested as container, then I would even consider having modulemd-url specified as an error.

**Comment by jscotka** [comment]
working on that in https://github.com/jscotka/meta-test-family/tree/module_type_split

**Comment by jscotka** [comment]
merged to devel branch
