### ISSUE TITLE
Provide a tag e.g. for Fedora for filtering out tests

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#82]
MTF should be able to filter out tests based on the whitelist/blacklist platform/version, e.g. Fedora, CentOS, SCL and the other.

Document how to use tags for real use cases.
Example is important. I would prefer to create section 'examples' in user_guide
http://meta-test-family.readthedocs.io/en/latest/user_guide/index.html

**Comment by phracek** [comment]
Question to this issue is, if it is relevant to https://github.com/fedora-modularity/conu/ or to `meta-test-family`.

**Comment by jscotka** [comment]
It is not related to MTF, neither CONU. 
It is related to used test framework, if you use MTF with avocado, avocado allows you to use tags for tests, so that you can filter out tests based on tags other frameworks has another ways how to do similar things see doc for avocado:
http://avocado-framework.readthedocs.io/en/54.0/WritingTests.html?highlight=tags#categorizing-tests

**Comment by phracek** [comment]
This is covered by #169

**Comment by phracek** [comment]
This is already fixed.
